version: 2.1

orbs:
  aws-parameter-store: circleci/aws-parameter-store@1.0.0

jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    environment:
      environment: development
    steps:
      - checkout
      - run:
          name: Setup Python Environment
          command: |
            export PATH=$PATH:/usr/local/bin:/home/circleci/.local/bin:
            pip install --upgrade --user pip 
            pip install -r requirements.txt
      - aws-parameter-store/load:
          filter: "Key=Name,Values=DB_PASSWORD"    
      - run:
          name: Install Terraform Binary
          command: |
            mkdir -p /tmp/terraform
            curl https://releases.hashicorp.com/terraform/0.12.10/terraform_0.12.10_linux_amd64.zip -o /tmp/terraform/terraform_0.12.10_linux_amd64.zip
            unzip /tmp/terraform/terraform_0.12.10_linux_amd64.zip -d /tmp/terraform/
      - run:
          name: Testing ParameterStore load
          command: |
            echo 'Print out ENV VAR DB_PASSWORD'
            echo ${DB_PASSWORD}
            echo 'Source parameterstore file'
            source /tmp/parameterstore/PARAMETERSTORESOURCEFILE
            echo ${DB_PASSWORD}
      - run:
          name: Runway Plan
          command: |
            export PATH=$PATH:/usr/local/bin:/home/circleci/.local/bin:/tmp/terraform
            export DEPLOY_ENVIRONMENT=$environment
            export CI=yes
            runway plan           
workflows:
  main:
    jobs:
      - build
