version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: Setup Python Environment
          command: |
            export PATH=$PATH:/usr/local/bin:/home/circleci/.local/bin:
            pip install --upgrade --user pip 
            pip install -r requirements.txt            
      - run:
          name: Install Terraform Binary
          command: |
            mkdir -p /tmp/terraform
            curl https://releases.hashicorp.com/terraform/0.12.10/terraform_0.12.10_linux_amd64.zip -o /tmp/terraform/terraform_0.12.10_linux_amd64.zip
            unzip /tmp/terraform/terraform_0.12.10_linux_amd64.zip -d /tmp/terraform/
      - run:
          name: Terraform Init
          command: |
            export PATH=$PATH:/usr/local/bin:/home/circleci/.local/bin:/tmp/terraform
            terraform init
workflows:
  main:
    jobs:
      - build
