version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: Setup Python Virtual Environment
          command: |
            pip install --upgrade --user pip 
            pip install -r requirements.txt            
      - run:
          name: Install Terraform Binary
          command: |
            mkdir -p /tmp/terraform
            https://releases.hashicorp.com/terraform/0.12.10/terraform_0.12.10_linux_amd64.zip -o /tmp/terraform/terraform_0.12.10_linux_amd64.zip
            unzip /tmp/terraform/terraform_0.12.10_linux_amd64.zip -d /tmp/terraform/
            cp /tmp/terraform/terraform /usr/local/bin/
      - run:
          name: Terraform Init
          command: terraform init
workflows:
  main:
    jobs:
      - build
